### ISSUE TITLE
How to test and demo

### ISSUE THREAD

**Issue by peoray** [siegerts/vue-component-library-template#13]
Thank you for this wonderful tutorial. I have a couple of questions:

- How do I add testing, I wish you added a sample in the tutorial. Do I have to nstall `vue-test-utils` as a devDependency?

- Also, how do I test the component I'm working on, there was no reference to this. I assume you made reference to this to this in the docs (not sure) but what if you just use a README as a doc and no need to use VuePress.

- If I want to use this component in my project, I assume I'd have to do Vue.use(componentName)` in my `main.js file? Rather than just install it and go ahead and import it in the component I want to use it. What's the difference between both approach?

**Comment by siegerts** [comment]
Hi @peoray !

- Yes, you can set up `vue-test-utils` and write tests for each component. If you are using the Vue CLI to build your project, you can use the plugin [cli-plugin-unit-jest](https://cli.vuejs.org/core-plugins/unit-jest.html) to run Jest tests.

- Not sure what you mean by this. A component test spec can be placed in each component directory and used to test that component.  The components are shown (i.e. documented) in the `.md` doc but it is still possible to test them as you normally would with Vue components. This is will not show in the generated output site.

- The template registers the plugin as a _global_ set of components to be used across your project. So, using `Vue.use(ComponentLibrary)` will make all of the components in the library available across your project.
