### ISSUE TITLE
Unknown custom element: <v-xxxxxxxx> - did you register the component correctly?

### ISSUE THREAD

**Issue by wdmtech** [siegerts/vue-component-library-template#5]
Seems related to https://github.com/vuejs/vuepress/issues/1173

To reproduce, clone the repo and then simply add another component (I just copied `standard-component` to create `another-component`)

Next, rebuild the project and click on your new component in the `/components` page. You will see the following error in the console:

![image](https://user-images.githubusercontent.com/7282262/61630847-ba209680-ac80-11e9-9e25-6e87573f11bc.png)

**Comment by wdmtech** [comment]
I've since forked the repo to demonstrate the issue:

https://github.com/wdmtech/vue-component-library-template

**Comment by siegerts** [comment]
Hi @wdmtech,  I cloned your fork locally and the component renders as expected (below) without error.  Wondering if there is a version mismatch somewhere?

![image](https://user-images.githubusercontent.com/634958/61636670-11fcd480-ac64-11e9-8d19-906d3706bd04.png)

**Comment by siegerts** [comment]
@wdmtech , does the issue still exist?

**Comment by wdmtech** [comment]
Wow, it works just fine in that fork - I think you might be right to suspect version mismatches. I'll keep digging.

**Comment by wdmtech** [comment]
Seems like bumping to `1.0.0-alpha.44` of Vuepress fixes the issue :-) I'm sorry to bother you with this! I'll let you know if anything else comes up. 

Thanks again for the great tutorial!

**Comment by siegerts** [comment]
No worries! Glad that you find it useful!
