### ISSUE TITLE
Code Injection

### ISSUE THREAD

**Issue by jdriesen** [siegerts/vue-component-library-template#9]
Hi @siegerts ,

First of all, thanks for sharing your code, and the wonderful documentation !
It's really a great help with documenting components.

Though, the code injection (in the <SourceCode> Component) , as explained on https://www.xiegerts.com/post/creating-vue-component-library-documentation/ doesn't always seem to work (I'm still getting the "old" code.

The "Code Example" sections uses the new code, so that's working fine.
Any idea what might go wrong ?

Thanks in advance for your reply,

Kind regards,
Johnny Driesen
Belgium

**Comment by siegerts** [comment]
Hey @jdriesen , I'm happy that you find it helpful.  You may need to rebuild ( stop -> `yarn docs:dev`) after you've made changes to the imported snippet.  This step happens before the webpack build and may not hot reload those changes if the server isn't restarted.

https://vuepress.vuejs.org/guide/markdown.html#import-code-snippets

Hopefully that helps!

**Comment by jdriesen** [comment]
Hi @siegerts ,

Thanks for your reply and the follow up.
Followed your suggestion, and everything is working now.

Thanks again for the support !

Kind regards,
Johnny Driesen
Belgium
